[alias]
clippy-strict = "lint"
doc-nightly   = ["--config", ".cargo/nightly.toml", "doc"]
doc-test      = ["test", "--doc"]
fmt-check     = ["fmt", "--check"]
lint          = ["clippy", "--all-targets", "--", "-D", "warnings"]
test-all      = ["test", "--all-targets", "--all-features"]

[build]
rustflags    = ["-D", "warnings"]
rustdocflags = ["-D", "warnings"]
